<?php

namespace Database\Seeders;

use App\Models\Work;
use Illuminate\Database\Seeder;
use Ramsey\Uuid\Uuid;

class WorkSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $data=[
            ['id'=>Uuid::uuid4(),'item_no'=>'5.1',	'pay_item'=>'Strut Berth -12.5m (Berth No.7)'	,	'unit'=>'','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.1.1'	,	'pay_item'=>'Piling works Supply and deliver to site of Steel Pipe Pile incl. toe reinforcement, shear key, hanging metal, welding, etc. ',	'unit'=>'m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.1.1.1)'	,	'pay_item'=>'Sea side: 1000mm dia x t=24 x L28.5m (SKK490) + 1000mm dia x t=17 x L 16.5m (SKK400) '	,	'unit'=>'m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.1.1.2)'	,	'pay_item'=>'Central: 1000mm dia x t=24 x L27.5m (SKK490) + 1000mm dia x t=17 x L 17.5m (SKK400) '	,	'unit'=>'m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.1.1.3)'	,	'pay_item'=>'Land side: 1000mm dia x t=24 x L27.5m (SKK400) + 1000mm dia x t=17 x L16.5m (SKK400) '	,	'unit'=>'m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.1.2'	,	'pay_item'=>'Supply and deliver to site of Steel Pipe Sheet Pile (SKY 400) including toe reinforcement, joint steel (P-P and P-T), welding etc. '	,	'unit'=>'m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.1.2.1)'	,	'pay_item'=>'Central: 1000mm dia x t=11 x L25.0m (SKY400)'	,	'unit'=>'m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.1.2.2)'	,	'pay_item'=>'800mm dia x t=11 x L25.0m (SKY400)'	,	'unit'=>'m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.1.3'	,	'pay_item'=>'Supply and delivery to site PC Joint Pile (600mm x 616mm), L=25m) '	,	'unit'=>'m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.1.4'	,	'pay_item'=>'Metal works Supply and deliver to site of submerged strut member including support materials, H-shape beam, grouting pipes.etc. '	,	'unit'=>'no.','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.1.4.1)'	,	'pay_item'=>'Sea side member for 1000mm dia of SPP'	,	'unit'=>'no.','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.1.4.2)'	,	'pay_item'=>'Central member for 1000mm dia of SPP'	,	'unit'=>'no.','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.1.5'	,	'pay_item'=>'Handle, pitch and drive Steel Pipe Pile'	,	'unit'=>'','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.1.5.1)'	,	'pay_item'=>'Sea side 1000mm dia of SPP, L=45.0m (Below MSL: 43.6m)'	,	'unit'=>'m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.1.5.2)'	,	'pay_item'=>'Central 1000mm dia of SPP, L=45.0m (Below MSL: 43.6m)'	,	'unit'=>'m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.1.5.3)'	,	'pay_item'=>'Land side 1000mm dia of SPP, L=44.0m (Below MSL: 42.6m)'	,	'unit'=>'m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.1.6'	,	'pay_item'=>'Handle, pitch and drive Steel Pipe Pile'	,	'unit'=>'','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.1.6.1)'	,	'pay_item'=>'1000mm dia x t=11 x L25.0m (Below MSL:23.6m)'	,	'unit'=>'m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.1.6.2)'	,	'pay_item'=>'800mm dia x t=11 x L25.0m (Below MSL:23.6m)'	,	'unit'=>'m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.1.7'	,	'pay_item'=>'Handle, pitch and driving of PC Joint Pile (600x616) including cutting, chipping and other incidental works  (Below MSL:23.6m)'	,	'unit'=>'m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.1.8'	,	'pay_item'=>'Install of submerged strut member including mortar grouting, welding etc.'	,	'unit'=>'no.','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.1.8.1)'	,	'pay_item'=>'Sea side member for 1000mm dia of SPP'	,	'unit'=>'no.','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.1.8.2)'	,	'pay_item'=>'Central member for 1000mm dia of SPP'	,	'unit'=>'no.','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.1.9'	,	'pay_item'=>'Corrosion protection system '	,	'unit'=>'','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.1.9.1)'	,	'pay_item'=>'Supply and install aluminum alloy anode (3.5A x 50Y) including steel, epoxy putty, welding, etc. '	,	'unit'=>'no.','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.1.9.2)'	,	'pay_item'=>'Supply and install potential measuring terminal including steel, welding, etc. '	,	'unit'=>'no.','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.1.9.3)'	,	'pay_item'=>'Supply and applying of protective coating (composite wrapping 6 layers)'	,	'unit'=>'m2','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.1.10'	,	'pay_item'=>'Deck Slab (Pier Head) Supply and placing of Class E concrete including support, welding, scaffolding, in-pile concrete, rubber bearing pads, anchor caps/bars etc., water hydrant pipe, formwork, reinforcement '	,	'unit'=>'cu.m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.1.11'	,	'pay_item'=>'Deck Slab (In-situ concrete) Supply and placing of Class B concrete including support, welding, scaffolding, steel cover, drain pipe, formwork, reinforcement ',	'unit'=>'cu.m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.1.12'	,	'pay_item'=>'Deck Slab (Coping Concrete for SPSP) Supply and placing of Class E concrete including reinforcement, support, in-pile concrete, welding, scaffolding, expansion joint, formwork, reinforcement ',	'unit'=>'cu.m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.1.13'	,	'pay_item'=>'PC deck slab'	,	'unit'=>'','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.1.13.1)'	,	'pay_item'=>'Supply and deliver PC deck slab (Type C)'	,	'unit'=>'no.','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.1.13.2)'	,	'pay_item'=>'Supply and deliver PC deck slab (Type D)'	,	'unit'=>'no.','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.1.13.3)'	,	'pay_item'=>'Install including tensioning, PC strand, bearings, concrete, formwork, re-bars, etc. of PC deck slab (Type C) '	,	'unit'=>'no.','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.1.13.4)'	,	'pay_item'=>'Ditto (Type D)'	,	'unit'=>'no.','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.1.14'	,	'pay_item'=>'Apron Concrete Placing apron concrete (Class B) 100mm thick including formwork, wire mesh, cutter joint, joint filler, sealing compound etc. ','unit'=>'m2','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.1.15'	,	'pay_item'=>'Miscellaneous works'	,	'unit'=>'','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.1.15.1)'	,	'pay_item'=>'Supply and install curbings including accessories'	,	'unit'=>'m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.1.15.2)'	,	'pay_item'=>'Supply and install rubber ladder including accessories'	,	'unit'=>'no.','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.1.15.3)'	,	'pay_item'=>'PDA Test including measurement of Setup Ratio'	,	'unit'=>'piles','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.2'	    ,	'pay_item'=>'Service Boat Berth (Berth No.8)'	,	'unit'=>'','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.2.1'	    ,	'pay_item'=>'Piling works'	,	'unit'=>'','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.2.1.1)'	,	'pay_item'=>'Supply and delivery to site PC Corrugated Sheet Pile "PCCSP" (W=950mm, B=1,246mm, L=25m) '	,	'unit'=>'m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.2.1.2)'	,	'pay_item'=>'Handle, pitch and driving of "PCCSP" (W=950, B=1,246mm) including cutting and other incidental works (Below MSL: 23.5m) '	,	'unit'=>'m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.2.2'	    ,	'pay_item'=>'Coping concrete works'	,	'unit'=>'','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.2.2.1)'	,	'pay_item'=>'Supply and install Tie wire F100T (7 x Φ11.1 ), L=21 m and other accessories including sleeves, nuts, plates, washers, trumpet sheaths etc.'	,	'unit'=>'set','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.2.2.2)'	,	'pay_item'=>'Supply and filling of concrete "Type E" including formwork, support, rebars and expansion joint (elastite), leveling concrete etc. '	,	'unit'=>'cu.m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.2.3'	,	'pay_item'=>'Slab anchorage works'	,	'unit'=>'','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.2.3.1)'	,	'pay_item'=>'Excavation of CPM soil above ±0.00m'	,	'unit'=>'cu.m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.2.3.2)'	,	'pay_item'=>'Supply and placement of Slab Anchorage as dimension shown on drawings including rebars, formwork, support, lifting hook, etc. '	,	'unit'=>'no.','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.2.3.3)'	,	'pay_item'=>'Supply, transportation, leveling, filling of rubble foundation (t=200mm)'	,	'unit'=>'cu.m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.2.4'	,	'pay_item'=>'Scour Protection'	,	'unit'=>'','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.2.4.1)'	,	'pay_item'=>'Supply, deliver, install and complete the Bamboo Mat works (3 layers) including testing, bamboo for stone fence, other incidental works '	,	'unit'=>'sq.m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.2.4.2)'	,	'pay_item'=>'Supply, levelling and placement of stones 5-20 kg works according to drawings and specifications '	,	'unit'=>'cu.m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.2.4.3)'	,	'pay_item'=>'Supply, levelling and placement of armor rock 100-250 kg works according to drawings and specifications '	,	'unit'=>'cu.m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.2.5'	,	'pay_item'=>'Apron pavement'	,	'unit'=>'','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.2.5.1)'	,	'pay_item'=>'Concrete pavement (t=300mm) including wire mesh, joints, tie-bars, dowel bars, rebars, joint sealers/fillers '	,	'unit'=>'m2','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.2.5.2)'	,	'pay_item'=>'Aggregate sub base course t=550mm'	,	'unit'=>'m2','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.2.5.3)'	,	'pay_item'=>'Sub grade preparation CBR>6%'	,	'unit'=>'m2','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.2.5.4)'	,	'pay_item'=>'Concrete curbing (class B / h=850mm) including leveling concrete (class D / t=100mm) with rubble mound '	,	'unit'=>'m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.2.6'	,	'pay_item'=>'Miscellaneous works'	,	'unit'=>'','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.2.6.1)'	,	'pay_item'=>'Supply and install curbings including necessary accessories'	,	'unit'=>'m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.2.6.2)'	,	'pay_item'=>'Supply and install rubber ladder including accessories'	,	'unit'=>'no.','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.2.6.3)'	,	'pay_item'=>'Supply and install fences including foundations and accessories'	,	'unit'=>'m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.3'	,	'pay_item'=>'RORO Berth'	,	'unit'=>'','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.3.1'	,	'pay_item'=>'Piling works'	,	'unit'=>'','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.3.1.1)'	,	'pay_item'=>'Supply and delivery to site PC Corrugated Sheet Pile "PCCSP" (W=700mm, B=1,246mm, L=22m) '	,	'unit'=>'m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.3.1.2)'	,	'pay_item'=>'Supply and delivery to site PC Joint Pile (500mm x 700mm), L=22m) '	,	'unit'=>'m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.3.1.3)'	,	'pay_item'=>'Supply and delivery to site PC Joint Pile (400mm x 650mm), L=22m) '	,	'unit'=>'m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.3.1.4)'	,	'pay_item'=>'Handle, pitch and driving of "PCCSP" (W=700, B=1,246mm) including cutting and any other incidental works (Below MSL:20.5m)'	,	'unit'=>'m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.3.1.5)'	,	'pay_item'=>'Handle, pitch and driving of PC Joint Pile (500mm x 700mm) including cutting, chipping and other incidental works (Below MSL:20.5m)'	,	'unit'=>'m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.3.1.6)'	,	'pay_item'=>'Handle, pitch and driving of PC Joint Pile (400mm x 650mm) including cutting, chipping and other incidental works (Below MSL:20.5m)'	,	'unit'=>'m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.3.2'	,	'pay_item'=>'Coping concrete works'	,	'unit'=>'','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.3.2.1)'	,	'pay_item'=>'Supply and install Tie wire F100T (7 x Φ11.1 ), L=21.2m and other accessories including sleeves, nuts, plates, washers, trumpet sheaths etc. for RO-RO berth '	,	'unit'=>'set','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.3.2.2)'	,	'pay_item'=>'Supply and install Tie wire F100T (7 x Φ11.1 ), L=22.5m and other accessories including sleeves, nuts, plates, washers, trumpet sheaths etc. for RAMP S-N '	,	'unit'=>'set','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.3.2.3)'	,	'pay_item'=>'Supply and install Tie wire F100T (7 x Φ11.1 ), L=30.25m and other accessories including sleeves, nuts, plates, washers, trumpet sheaths etc. for RAMP E-W '	,	'unit'=>'set','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.3.2.4)'	,	'pay_item'=>'Supply and filling of concrete "Type E" including support, expansion joints, levelling concrete, formwork, reinforcement for RORO berth and Ramp '	,	'unit'=>'cu.m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.3.3'	,	'pay_item'=>'Slab anchorage works'	,	'unit'=>'','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.3.3.1)'	,	'pay_item'=>'Excavation of CPM soil'	,	'unit'=>'cu.m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.3.3.2)'	,	'pay_item'=>'Supply and placement of Slab Anchorage as dimension shown on drawings including rebars, formwork, support, lifting hook, tie-wire sheath'	,	'unit'=>'no.','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.3.3.3)'	,	'pay_item'=>'Supply, transportation, leveling, filling of rubble foundation (t=200mm)'	,	'unit'=>'cu.m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.3.4'	,	'pay_item'=>'Foundation of 1000kN mooring post (Type A & B)'	,	'unit'=>'','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.3.4.1)'	,	'pay_item'=>'Supply and filling of concrete "Class B" including formwork, support, rebars, etc. '	,	'unit'=>'cu.m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.3.4.2)'	,	'pay_item'=>'Supply, transportation, leveling, filling of rubble foundation (t=200mm)'	,	'unit'=>'cu.m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.3.5'	,	'pay_item'=>'Concrete Revetment for Ramp'	,	'unit'=>'','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.3.5.1)'	,	'pay_item'=>'Supply and placement of In-situ concrete "Class C" including formwork, support, etc. for Retaining walls '	,	'unit'=>'cu.m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.3.6'	,	'pay_item'=>'Scour Protection'	,	'unit'=>'','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.3.6.1)'	,	'pay_item'=>'Supply, deliver, install and complete the Bamboo Mat works (3 layers) including testing and other incidental works '	,	'unit'=>'sq.m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.3.6.2)'	,	'pay_item'=>'Supply, levelling and placement of armor stone 200-500 kg works according to drawings and specifications '	,	'unit'=>'cu.m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.3.7'	,	'pay_item'=>'Apron pavement'	,	'unit'=>'','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.3.7.1)'	,	'pay_item'=>'Concrete pavement (t=300mm) including wire mesh, joints, tie-bars, dowel bars, rebars, joint sealers/fillers '	,	'unit'=>'m2','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.3.7.2)'	,	'pay_item'=>'Aggregate sub base course t=550mm'	,	'unit'=>'m2','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.3.7.3)'	,	'pay_item'=>'Sub grade preparation CBR>6%'	,	'unit'=>'m2','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.3.7.4)'	,	'pay_item'=>'Concrete curbing (class B / h=850mm) including leveling concrete (class D / t=100mm) with rubble mound '	,	'unit'=>'m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.3.8'	,	'pay_item'=>'Miscellaneous works'	,	'unit'=>'','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.3.8.1)'	,	'pay_item'=>'Supply and install curbings including necessary accessories'	,	'unit'=>'m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.3.8.2)'	,	'pay_item'=>'Supply and install rubber ladder including necessary accessories'	,	'unit'=>'no.','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.3.8.3)'	,	'pay_item'=>'Supply and install fences including foundations and necessary accessories '	,	'unit'=>'m','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.3.8.4)'	,	'pay_item'=>'Supply and install gates (L=10m) including foundations and necessary accessories '	,	'unit'=>'no.','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.4'	,	'pay_item'=>'Fender and bollard'	,	'unit'=>'','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.4.1)'	,	'pay_item'=>'Supply and install cell type fender (1000H) for Car Berth including all relevant accessories '	,	'unit'=>'no.','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.4.2)'	,	'pay_item'=>'Supply and install V-type fender (V400Hx2800L) for Service Boat Berth including all relevant accessories '	,	'unit'=>'no.','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.4.3)'	,	'pay_item'=>'Supply and install double cell type fender (800H) for Ro-Ro Berth including all relevant accessories '	,	'unit'=>'set','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.4.4)'	,	'pay_item'=>'Supply and install V-type fender (1000H, L=2.0m) for Ro-Ro Ramp including all relevant accessories '	,	'unit'=>'no.','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.4.5)'	,	'pay_item'=>'Supply and install bollard (1000kN) for Car Berth including all relevant accessories '	,	'unit'=>'no.','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.4.6)'	,	'pay_item'=>'Supply and install bollard (150kN) for Service Boat Berth including all relevant accessories '	,	'unit'=>'no.','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.4.7)'	,	'pay_item'=>'Supply and install bollard (700kN) for Ro-Ro Berth including all relevant accessories '	,	'unit'=>'no.','created_by'=>1],
            ['id'=>Uuid::uuid4(),'item_no'=>'5.4.8)'	,	'pay_item'=>'Supply and install mooring bit (1000kN) for Ro-Ro Ramp including all relevant accessories '	,	'unit'=>'no.','created_by'=>1]
            ];
            Work::insert($data);
        }
}
